networks:
  app-network:
    driver: bridge

services:
  # Frontend - React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/home/node/app  # Syncs local changes to container
      - /home/node/app/node_modules # Keeps node_modules isolated within the container
    environment:
      - CHOKIDAR_USEPOLLING=true # Enables file watching for hot-reloading in Docker
    networks:
      - app-network
